[package]
name = "day-01"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "day-01-benchmarks"
path = "benches/benchmarks.rs"
harness = false
