[package]
name = "day-05"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "day-05-benchmarks"
path = "benches/benchmarks.rs"
harness = false
